widget_huli/forum/urls.py
from django.urls import path
from . import views
from .views import (ForumViews, ForumPostDetails, 
                    ForumPostNew, ForumPostEdit)

urlpatterns = [
    path('', views.ForumViews, name='forum'),
    path('forumposts/<int:pk>/details/', ForumPostDetails.as_view(), name="forumpostdetails"),
    path('forumposts/add/', ForumPostNew.as_view(), name='forumpostnew'),
    path('forumposts/<int:pk>/edit/', ForumPostEdit.as_view(), name = 'forumpostedit'),
]

app_name = "forum"

widget_huli/widget_huli/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('forum/', include(('forum.urls', 'forum'), namespace="forum" )),
    path('assignments/', include(('assignments.urls', 'assignments'), namespace="assignments")),
    path('dashboard', include(('dashboard.urls', 'dashboard'), namespace="dashboard")),
    path('admin/', admin.site.urls),
]

widget_huli/forum/models.py
from django.db import models
from django.urls import reverse
from dashboard.models import WidgetUser

# Create your models here.
class ForumPost(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    author = models.ForeignKey(
        WidgetUser,
        on_delete=models.CASCADE
    )
    pub_datetime = models.DateTimeField()
    
    class Meta:
        ordering = ['-pub_datetime']
    
    def __str__(self):
        return '{}'.format(self.title)
    
    def get_absolute_url(self):
        return reverse("forum:forumpostdetails", kwargs={"pk": self.pk})

class Reply(models.Model):
    body = models.TextField()
    author = models.CharField(max_length=50)
    pub_datetime = models.DateTimeField()
    forum_post = models.ForeignKey(
        ForumPost,
        on_delete=models.CASCADE
    )
    def get_absolute_url(self):
        return reverse("forum:replydetails", kwargs={'pk': self.pk})

widget_huli/forum/forms.py
from django import forms
from .models import ForumPost

class ForumPostForm(forms.ModelForm):
    pub_datetime = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'],
                                       widget = forms.DateTimeInput(format = '%d/%m/%Y %H:%M',
                                                                    attrs = {'class': 'form-control'}),
                                       label = 'Date and Time')
    class Meta:
        model = ForumPost
        fields = '__all__'
    

widget_huli/forum/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import DetailView, CreateView, UpdateView

from .models import ForumPost, Reply
from .forms import ForumPostForm

# Create your views here.

def ForumViews(request):
    forum = ForumPost.objects.all()
    context = {'forum':forum}
    return render(request, 'forum/forum.html', context)

class ForumPostDetails(DetailView):
    template_name= "forum/forumpost-details.html"
    model = ForumPost
                                    
class ForumPostNew(CreateView):
    form_class = ForumPostForm
    template_name = "forum/forumpost-add.html"
    
    def get_success(self):
        return reverse('forum:forumpostnew', kwargs = {'pk': self.object.id}, 
                    current_app=self.request.resolver_match.namespace)
    
class ForumPostEdit(UpdateView):
    form_class = ForumPostForm
    template_name = "forum/forumpost-edit.html"
    queryset = ForumPost.objects.all()
    
    def get_success_url(self):
        return reverse('forum:forumpostdetails', kwargs = {'pk': self.object.pk}, 
                       current_app=self.request.resolver_match.namespace)

widget_huli/forum/templates/forum/forum.html
{%extends "base.html"%}

{%block title %}Widget's Forum{%endblock%}
{%block header %}Welcome to Widget's Forum!{%endblock %}
{%block body %}
<h2>Forum Posts:</h2>
{% for post in forum%}
<a href="{% url 'forum:forumpostdetails' post.pk%}">
    {{post.title}} by {{post.author.first_name}} {{post.author.last_name}}<br>
</a>
{%endfor%}

<br>
<a href="{%url 'forum:forumpostnew' %}">
    <input type="button" value= "New Post"></a>
<br>
<br>
<a href= "/dashboard">Dashboard</a><br>
<a href= "/assignments/">Assignments</a>
<br>

{% endblock%}

widget_huli/forum/templates/forum/forumpost-add.html
{%extends "base.html"%}


{%block title %}Add Post{%endblock%}

{%block header %}Add a new post:{%endblock %}
{%block body %}
<form method= "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type= "submit" value="Save New Post">
</form>

{% endblock%}

widget_huli/forum/templates/forum/forumpost-details.html
{%extends "base.html"%}


{%block title %}{{object.title}}{%endblock%}


{%block header %}{{object.title}}{%endblock %}
{%block body %}
by {{object.author.first_name}} {{object.author.last_name}}<br>
{{object.pub_datetime}}<br>
{{object.body}}<br>
<br>
<br>
POST REPLIES:
<br>
{% for reply in object.reply_set.all%}
{{reply.author}}<br>
{{reply.pub_datetime}}<br>
{{reply.body}}<br>
<br>
{%endfor%}
<a href="{%url 'forum:forumpostedit' object.pk %}">
    <input type="button" value= "Edit Post"></a>
<br>

{% endblock%}

widget_huli/forum/templates/forum/forumpost-edit.html
{%extends "base.html"%}


{%block title %}Edit Post{%endblock%}

{%block header %}Edit Post:{%endblock %}
{%block body %}
<form method= "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type= "submit" value="Save Changes to Post">
</form>

{% endblock %}